In [2]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; 
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Матрицу $A$ можно умножить не на всякую матрицу $B$: __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

a) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$ в матрице A 2 столбца, а в матрице В 4 строки, поэтому произведение АВ не определено и произведение ВА также не определено;

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$ в матрице A 5 столбцов, а в матрице В 5 строк, поэтому произведение АВ определено, но произведение ВА не определено т.к. в матрице В 3 столбца, а в матрице А 2 строки

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; в матрице A 3 столбца, а в матрице В 3 строки, поэтому произведение АВ определено, также произведение ВА определено т.к. в матрице В 8 столбцов, а в матрице А 8 строк

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. в матрице A 4 столбца, а в матрице В 4 строки, поэтому произведение АВ определено, также произведение ВА определено т.к. в матрице В 4 столбца, а в матрице А 4 строки

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ и $AB=\begin{pmatrix}
((1*4)+(-2*0)) & ((1*-1)+(-2*5))\\ 
((3*4)+(0*0)) & ((3*-1)+(0*0))
\end{pmatrix}=\begin{pmatrix}
2 & -11\\ 
12 & -3
\end{pmatrix}$

In [25]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'A+B={a+b}')
print(f'A*B={np.dot(a,b)}')


A+B=[[ 5 -3]
 [ 3  5]]
A*B=[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$,
$3A-2B+4C=\begin{pmatrix}
(3-0+8) & (21-10-16)\\ 
(9-4+4) & (-18+2+4)
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$


In [26]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'3A-2B+4C={3*a - 2*b + 4*c}') 

3A-2B+4C=[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$



$AA^{T}=\begin{pmatrix}
((4*4)+(1*1)) & ((4*5)+(1*-2)) & (4*2 + 1*3)\\ 
((5*4)+(-2*1) & ((5*5)+(-2*-2) & (5*2 + (-2)*3)\\
((2*4)+(3*1)) & ((2*5)+(3*-2) & (2*2 + 3*3)                 
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13               
\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
((4*4)+(5*5)+(2*2)) & ((4*1)+(5*-2)+(2*3))\\ 
((1*4)+(-2*5)+(3*2)) & ((1*1)+(-2*-2)+(3*3))
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [27]:
a = np.array([[4,1], [5,-2], [2,3]])
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [28]:
print(f'A*AT={np.dot(a,a.T)}')
print(f'AT*A={np.dot(a.T,a)}')

A*AT=[[17 18 11]
 [18 29  4]
 [11  4 13]]
AT*A=[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.